feat(cli): add output flag to service account create cmd
brigadecore/brigade pull request #1459
Opened 2021-06-25 16:24 UTC by vdice

**What this PR does / why we need it**:

* Adds an output format flag to the `brig service-acccount create` command.  This will be handy for automation to quickly/easily parse the returned token value.

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2021-06-25 19:54 UTC, vdice commented
Note: CI is hitting the (unrelated; occurs on v1 branch) unit test failure in https://github.com/brigadecore/brigade/issues/1460.

2021-06-26 00:25 UTC, krancour requested changes

2021-06-26 00:25 UTC, krancour commented on v2/cli/service_account_commands.go
We need to deal with invalid flag values.

2021-06-29 15:58 UTC, krancour approved these changes
LGTM

2021-06-29 20:59 UTC, merged